#Run this makefile once and with 1 thread.
CPUS=3

all: maxdb pgsqla pgsqln mysql maxdb

Makefile.pgsqla: make-single-class-arff-files.pl
	perl make-single-class-arff-files.pl pgsqla
pgsqla: 
	make -f Makefile.pgsqla -j $(CPUS) all
	touch pgsqla

Makefile.pgsqln: make-single-class-arff-files.pl
	perl make-single-class-arff-files.pl pgsqln
pgsqln: 
	make -f Makefile.pgsqln -j $(CPUS) all
	touch pgsqln

Makefile.mysql: make-single-class-arff-files.pl
	perl make-single-class-arff-files.pl mysql
mysql: 
	make -f Makefile.mysql -j $(CPUS) all
	touch mysql


Makefile.maxdb: make-single-class-arff-files.pl
	perl make-single-class-arff-files.pl maxdb
maxdb: 
	make -f Makefile.maxdb -j $(CPUS) all
	touch maxdb


#perl make-single-class-arff-files.pl pgsqln && make -f Makefile.pgsqln -j $(CPUS) all
#perl make-single-class-arff-files.pl pgsql && make -f Makefile.pgsql -j $(CPUS) all
#perl make-single-class-arff-files.pl mysql && make -f Makefile.mysql -j $(CPUS) all
#perl make-single-class-arff-files.pl maxdb && make -f Makefile.maxdb -j $(CPUS) all
#perl make-single-class-arff-files.pl maxdb__mysql && make -f Makefile.maxdb__mysql -j $(CPUS) all
