* Last minute todo [32/40]
  - [X] Ric Edits
  - [X] Our data and scripts are available at http://softwareprocess. es/icpc2010
    Pick a conference neutral-name!
    (Suggestion of the top of my head: "nomen", Latin for "name")
  - [X] probably best to hyphenate "non-functional" but check all
    instances, as you are inconsistent.
  - [X] Slightly tweaked abstract:

    Within the field of mining software repositories, many approaches,
    such as topic modeling and concept location, rely on the automated
    application of machine learning algorithms to corpora.
    This kind  of approach typically makes no use of domain-specific knowledge to
    improve the results or put them into a context that a developer
    can relate to.  
    While too much specificity can produce
    non-generalizable results, too little produces broad learners that
    do not provide much immediately useful detail. 
    In this paper, we
    investigate what topics the latent topics classifier produces, and
    examine whether such topics can be generalized across software
    products. 
    We focus on non-functional requirements related to
    software quality as a potential generalization, since there is
    some shared belief that these qualities apply broadly across many
    software systems and their development artifacts.
    In our
    approach, we name topics based on a static ontology of
    non-functional requirements and software qualities; in essence,
    this adds context to general-purpose ontologies such as
    Wordnet. 
    In this paper, we discuss how we use this software
    development domain knowledge to better annotate topics of
    development that are extracted from the change log messages in
    configuration management systems such as CVS.  
    Since our taxonomy
    is global in scope, our results allow us to compare the relative
    importance of particular qualities across different projects.

        important:   You need to conclude the abstract with a summary of the study you did and some indication of the results to make them realize this isn't just an "I built it" paper.  ie you tried it out and have real results.

        Abstracts in FSE submissions are particularly important!
  - [X] Cite Mulan \XXX{Maybe cite these}
  - [X] Conclusions
  - [X]  "the latent topics extractors produces,"  
	 plural or sing?  need to fix agreement.
  - [X]  "acceptable results"  
	What if you're easy to please?  :-)   Can you detail a bit what this means?
  - [X]-- "a lot of loss" -> "much loss"
	but loss relative to what?  What were you optimizing against?
  - [X] XXX{exp2}
  - [ ] XXX{should have mysql}
  - [ ] Abstract is a little long, but I'm not sure how to compress it.
  - [X] Comparing MaxDB and MySQL
  - [X] "self identify themselves"
	  redundant: "self identify" or "identify themselves"
  - [X] "If a topic has a name or a label we immediately have a good
        idea of what it is. In our case the name is the bit of
        information, the summary, that was missing from our topics to
        make them useful and complete. Although we are convinced that
        accurate naming is not completely feasible, so we have
        focussed on labelling topics by non-functional requirements."

         This paragraph is confusing to me.  You already said that a
         topic is a word distribution, but how would it get a label
         unless we select one?  How about this:

     A topic --- that is, a word distribution in our world --- needs a
     suggestive name to succinctly convey its intent, and make it easy
     to use in discussions and analyses about the development of the
     system.  Our previous experience leads us to believe that
     automated topic naming is currently infeasible in the general
     case, so we have decided to focus on topic labels from the
     subdomain of non-functional requirements.


  - [X] Classifying topics - mention all of the learners we used!

  - [X] " to partially control for differences in functional requirements."

    Not sure what you mean by this.  How about this:

    To evaluate our approach, we sought candidate systems that were
    mature projects and had openly accessible artifact repositories.
    We also decided to select systems from the same application
    domain, as we felt the functional requirements would probably be
    broadly similar.

  -  [why is this important?]   We selected MySQL and MaxDB [...]

  - [X]
      Our second list, exp2, relied on the ISO quality model (ISO9126)
      [1]. It describes six high-level quality requirements (listed in
      Table 1). There is some debate about the significance and
      importance of the terms in this model. However, it is
       ...

     - I would nuke most of this paragraph as it sounds too defensive.  

     - Who debates this standard, exactly?

     - "User friendly" is a dangerous term, as it's basically
       meaningless (it's often cited as an example of a motherhood
       requirement, which no one would ever not want).  Is there
       another one you could substitute in?


  - [X] What words did J48 like?
  - [X] Clean up mulan tables
  - [X] Table capitalization
  - [X] Table captions below!
  - [X] Are tables referenced?
  - [X] Are all tables and figures referenced?
  - [X] Edit related work
  - [X] Spellcheck
  - [X] Edit Abstract
  - [X] Edit Intro
  - [X] Edit Background
  - [X] Edit Methodology
  - [X] Edit Word List similarity
  - [X] ...
  - [X] Spellcheck
  - [X] Review our observation emails
  - [ ] Go over abstract again
  - [ ] Ensure that our research questions are clarified
        They were asked in sec:suplearn
  - [ ] Check bibtex for backwards author order!
  - [ ] Fix Fmeasure thing - parse confusion matrix
  - [ ] hires images!
  - [ ] 10 pages
   


* Paper todo for icpc2010.tex
** Schedule it
*** Friday Feb 26
    - [X] Get mulan results?
*** Saturday Feb 27    
    - [X] Get mulan results?
*** Sunday Feb 28    
    - Write
    - [X] Visualization?
*** Monday Mar 1
    - Write
*** Tuesday Mar 2
    - Lisp Users Group
    - Write
*** Wednesday Mar 3
    - Draft Due!
    - Freeze & Edit
*** Thursday Mar 4
    - Edit Hard!
    - Freeze and Edit
*** Friday Mar 5
    - Freeze Edit
    - Submit
** Data
   - [ ] Do postgresql
   - [ ] Another one
** Abstract [/]
   - [ ] Edit
   - [ ] Use Steve's abstract style
** Introduciton [/]
   - [ ] para1 last sentence
   - [ ] 
** Background [/]
   - [ ] Mining
   - [ ] IR
** Terminology [/]
** Supervised Learning [/]
   - [ ] Cover the learners
   - [ ] Cover the concept
** Associating Labels [/]
   - [ ] Cite Mockus et al
** Word list similarity [/]
   - [ ] Describe the method
** Classifying topics
   - [ ] Summarize 

